import {Component, Input, OnInit} from '@angular/core';

@Component({
    selector: 'app-newsletter-body',
    templateUrl: './newsletter-body.component.html',
    styleUrls: ['./newsletter-body.component.scss']
})
export class NewsletterBodyComponent implements OnInit {
    @Input() pageLang: string;

    strengths = [];
    benefits = [];

    strengthEn = [
        {
            title: 'Personalized consumer profiles',
            text: 'A.I. builds consumer profiles for each individual user by recording and learning from their behaviour and choices on the platform. It also utilizes an optional questionnaire available both during platform enrollment and in the user profile settings menu.'
        }, {
            title: 'Optimized recommendations based on user profiles',
            text: 'A.I. queries the platform\'s databases, generating optimized options and recommendations correlated with users\' consumer profiles. These recommendations encompass all services and offerings provided by our contracted partners.'
        }, {
            title: 'Personalized travel itineraries',
            text: 'A.I. generates comprehensive travel itineraries by correlating destinations and services offered by our partners with consumer profiles.'
        }, {
            title: 'Virtual concierge in your pocket',
            text: 'A.I. provides users with the privilege of having a permanent virtual concierge in their pocket through the Natural Language ChatBot function. In conclusion, A.I. incorporates an advance'
        },
    ]
    strengthRo = [
        {
            title: 'Profiluri de utilizatori personalizate',
            text: 'A.I. creează profiluri de consumator pentru fiecare utilizator prin înregistrarea și învățarea comportamentului și alegerilor acestora pe platformă. Acesta folosește un chestionar opțional disponibil atât în timpul înregistrării pe platformă cât și în meniul cu setările profilului de utilizator.'
        }, {
            title: 'Recomandări optimizate bazate pe profilurile utilizatorilor',
            text: 'A.I. interoghează bazele de date ale platformei, generând opțiuni și recomandări optimizate corelate cu profilurile de consumator ale utilizatorilor. Aceste recomandări înglobează toate serviciile și ofertele furnizate de către partenerii noștri contractați.'
        }, {
            title: 'Itinerarii personalizate de călătorie',
            text: 'A.I. generează itinerarii complete de călătorie prin corelarea destinațiilor și serviciilor oferite de către partenerii noștri cu profilurile consumatorilor.'
        }, {
            title: 'Un concierge virtual în buzunarul dumneavoastră',
            text: 'A.I. oferă utilizatorilor privilegiul de a avea un concierge virtual permanent în buzunarul lor prin funcția Natural Language ChatBot.'
        },
    ]

    benefitsEn = [
        'Bestinform\'s own Channel Manager and payment processor enable partners to upload their availability without requiring a Property Manager System. This ensures a seamless flow of purchases and reservations, providing a complete acquisition and booking process.',
        'There is the possibility to connect a partner\'s Property Manager System to the Bestinform platform through API documentation, ensuring a complete flow of purchases and reservations.',
        'The possibility of facilitating bookings with guarantee deposits is available.',
        'The possibility of facilitating bookings with partial payments is available.',
        'The possibility of facilitating purchases.',
        'Correct display of service providers\' addresses.',
        'Intuitive and user-friendly dashboard for managing property bookings/purchases.',
        'Aligning the services and facilities of the resource with potential customers through the mechanism described in the AI chapter.',
        'Integration of the property into travel itineraries generated by A.I. based on user profiles.',
        'User-friendly reservation tracking menu.',
        'User-friendly balance tracking menu.',
        'The ability to upload multimedia content.',
        'The ability to upload menus, prices, and ICON products to facilitate easier identification of the solutions offered by the property and promote them within the platform.',
        'The ability to receive special requests at the time of booking.',
        'The ability to cancel a reservation without a deposit if the user\'s rating is unfavorable.',
        'A complex system for loading availability based on multiple time intervals within a day (breakfast - break - lunch + dinner), calendar date, time, reserved facility type, number of guests, standard price, discount, limited-time offer, guarantee deposit, configuring reservation slot time with automatic reset (exclusive for restaurants), price category, class, and location (access tickets: cinema, theater, opera, concert, museum, exhibition, zoo, etc.).'
    ]

    benefitsRo = [
        'Managerul de Canal și procesatorul de plăți Bestinform permit partenerilor să încarce disponibilitatea acestora fără să solicite un Sistem de Administrare a Proprietății. Aceasta asigură un flux lin al achizițiilor și al rezervărilor, oferind un proces complet de achiziție și rezervare.',
        'Există posibilitatea de a conecta un Sistem de Administrare a Proprietății al unui partener la platforma Bestinform prin intermediul documentației API, asigurând un flux complet de achiziții și rezervări.',
        'Există posibilitatea facilitării rezervărilor cu depozite de garanție.',
        'Este disponibilă posibilitatea facilitării rezervărilor cu plăți parțiale.',
        'Posibilitatea facilității achizițiilor.',
        'Afișarea corectă a adreselor furnizorilor de servicii.',
        'Tablou de bord intuitiv și ușor de utilizat pentru administrarea rezervărilor/achizițiilor de proprietăți.',
        'Alinierea serviciilor și facilităților de resurse cu potențialii clienți prin intermediul mecanismului descris în capitolul AI.',
        'Integrarea proprietății în itinerariile de călătorie generate de A.I. pe baza profilurilor de utilizator.',
        'Meniu de urmărire a rezervării ușor de utilizat.',
        'Meniu de urmărire a soldului ușor de utilizat.',
        'Capacitatea de a încărca conținut multimedia.',
        'Capacitatea de a încărca meniuri, prețuri și produse ICON pentru o identificare mai rapidă a soluțiilor oferite de proprietate și promovarea acestora pe platformă.',
        'Capacitatea de a primi cereri speciale în momentul rezervării.',
        'Capacitatea de a anula o rezervare fără plata unui avans dacă rating-ul utilizatorului este nefavorabil.',
        'Un sistem complex de încărcare a disponibilității în funcție de mai multe intervale de timp într-o zi (micul dejun – pauză – prânz + cină), data calendaristică, ora, tipul facilității rezervate, numărul de oaspeți, prețul standard, discount-ul, ofertă pe o perioadă limitată, garanție, configurarea perioadei rezervării cu resetare automată (exclusiv pentru restaurante), categoria de preț, clasa și locația (bilete de acces: cinema, teatru, operă, concert, muzeu, expoziție, zoo, etc.)'
    ]

    ngOnInit() {
        console.log('page lang', this.pageLang);
        if (this.pageLang === 'ro') {
            console.log('am intrat');
            this.strengths = this.strengthRo;
            this.benefits = this.benefitsRo;
        } else {
            this.strengths = this.strengthEn;
            this.benefits = this.benefitsEn;
        }
    }


}
