export const AirCompaniesLibrary = {
    A3: "assets/images/others/planes/companies/A3.png",
    AF: "assets/images/others/planes/companies/AF.jpg",
    AF_HOP: "assets/images/others/planes/companies/AF_HOP.png",
    AZ: "assets/images/others/planes/companies/AZ.png",
    BA: "assets/images/others/planes/companies/BA.jpg",
    EN: "assets/images/others/planes/companies/EN.png",
    EZ: "assets/images/others/planes/companies/EZ.jpg",
    FR: "assets/images/others/planes/companies/FR.jpg",
    FZ: "assets/images/others/planes/companies/FZ.jpg",
    H7: "assets/images/others/planes/companies/H7.png",
    H4: "assets/images/others/planes/companies/H7.png",
    IB: "assets/images/others/planes/companies/IB.png",
    JU: "assets/images/others/planes/companies/JU.png",
    KL: "assets/images/others/planes/companies/KL.jpg",
    KM: "assets/images/others/planes/companies/KM.png",
    LG: "assets/images/others/planes/companies/LG.jpg",
    LH: "assets/images/others/planes/companies/LH.png",
    LO: "assets/images/others/planes/companies/LO.png",
    LX: "assets/images/others/planes/companies/LX.jpg",
    NG: "assets/images/others/planes/companies/NG.png",
    OS: "assets/images/others/planes/companies/OS.jpg",
    PC: "assets/images/others/planes/companies/PC.png",
    QR: "assets/images/others/planes/companies/QR.jpg",
    RO: "assets/images/others/planes/companies/RO.png",
    TK: "assets/images/others/planes/companies/TK.jpg",
    TP: "assets/images/others/planes/companies/TP.jpg",
}
